name: mask_alert
description: 개인 건강 프로필 기반 맞춤형 미세먼지 마스크 착용 알림 앱
publish_to: 'none'
version: 1.0.4+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  flutter_riverpod: ^2.5.1

  # 로컬 저장
  shared_preferences: ^2.2.3

  # 알림
  flutter_local_notifications: ^17.2.2

  # 백그라운드 작업
  workmanager: ^0.9.0

  # HTTP 통신
  dio: ^5.4.3+1

  # 위치
  geolocator: ^13.0.1

  # 광고
  google_mobile_ads: ^5.1.0

  # 권한
  permission_handler: ^11.3.1

  # 아이콘
  cupertino_icons: ^1.0.6
  firebase_core: ^4.6.0
  firebase_analytics: ^12.2.0
  firebase_crashlytics: ^5.1.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
